# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0004_auto_20171016_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donor',
            new_name='name',
        ),
    ]
