# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0006_cfp_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfp',
            name='slug',
        ),
    ]
