# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:17
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
from cfp.models import Cfp


def migrate_data_forward(apps, schema_editor):
    for instance in Cfp.cfp.all():
        print("Generating slug for {}".format(instance))
        instance.save()

def migrate_data_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_remove_cfp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backwards,
        ),
    ]
