# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0011_cfp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfp',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=255, null=True, populate_from='title', unique=True),
        ),
    ]
