# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('no_of_pieces', models.IntegerField()),
            ],
            options={
                'ordering': ('item',),
            },
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('stock_in_or_out', models.CharField(choices=[('IN', 'Stock coming in'), ('OUT', 'Stock going out')], max_length=3)),
                ('supplier', models.CharField(blank=True, max_length=20)),
                ('document_no', models.CharField(max_length=50)),
                ('stock_amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Country')),
            ],
            options={
                'ordering': ('town',),
            },
        ),
        migrations.AddField(
            model_name='stockcard',
            name='to_where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Town'),
        ),
    ]
